# Generated by Django 2.1.7 on 2019-03-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
    ]
